### ISSUE TITLE
Placeholder does not respect region priority.

### ISSUE THREAD

**Issue by chezzzer** [firewolf8385/RegionDisplayName#1]
Hello! Massively awesome plugin for location status in RPG maps and event maps.

The only problem is we have a bunch of regions that overlap, our previous solution for location status respected worldguard's inbuilt region priority system to show which region. So the placeholder returns the region with the highest priority. Can this be implemented?

**Comment by firewolf8385** [comment]
Sorry, just seeing this now. I wasn't aware of region priorities before, thank you. This should be fixed in 1.2: https://github.com/JadedMC/RegionDisplayName/releases/tag/1.2
