### ISSUE TITLE
__global__ region display name not working

### ISSUE THREAD

**Issue by javiertdev** [firewolf8385/RegionDisplayName#2]
Incredible plugin, allows you to do incredible things!

I think there is an error or maybe, I don't know how to use it very well, but the display name of the __global__ region does not work.

Is this a bug, or is it simply not possible to do this?

**Comment by javiertdev** [comment]
I've been doing some more research and noticed that it doesn't work with MultiVerse and only allows one __global__ for all worlds.
It would be great if this could be implemented, thanks and sorry for listing it as a bug.

**Comment by firewolf8385** [comment]
~~It's been a hot minute since I made this, so I could be wrong, but I believe the reason was that the global region doesn't exist as an actual region in the WorldGuard API. I should probably specify that somewhere.~~

As a bypass I think I could just make it check for world name if it doesn't find any valid regions, so that you'd configure the world name the same exact way you would region name.

**Comment by javiertdev** [comment]
I understand, thank you very much!

**Comment by firewolf8385** [comment]
This version should let you use world names: https://www.jadedmc.net/plugins/RegionDisplayName/RegionDisplayName%20v1.3b1.jar

**Comment by javiertdev** [comment]
Wow, that's fast, what should the syntax be?
Will the base world take the world name or MultiVerse alias?

Example:
nameworld: overworld
alias: &2&lSurvival

**Comment by firewolf8385** [comment]
Same format as before, just with the world name replacing the region name. So instead of
```
Regions:
  __global__: "&7None"
```

You'd have
```
Regions:
  world: "&7Overworld"
  world_nether: "&7Nether"
  world_end: "&fThe End"
```

And yeah, it takes the actual name of the world and not multiverse alias for the key

**Comment by javiertdev** [comment]
That's great, it works wonderfully, a detail I found, maybe it would be good to make it so that if a region does not have DisplayName defined, it takes the world's DisplayName by default.

Thank you very much for taking the time to help me, I appreciate it very much.

**Comment by firewolf8385** [comment]
That should be how it already works? It checks for regions first, and if it doesn't find one it checks for worlds next. Then if it finds neither, it goes to the configured "Default".

All of the settings support placeholders, so if you mean setting "Default" to be the world name, you can just use the placeholder that gets the current world's name.
